/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IdentityProvider } from "./IdentityProvider";
import { IdentityProviderCountArgs } from "./IdentityProviderCountArgs";
import { IdentityProviderFindManyArgs } from "./IdentityProviderFindManyArgs";
import { IdentityProviderFindUniqueArgs } from "./IdentityProviderFindUniqueArgs";
import { DeleteIdentityProviderArgs } from "./DeleteIdentityProviderArgs";
import { IdentityProviderService } from "../identityProvider.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => IdentityProvider)
export class IdentityProviderResolverBase {
  constructor(
    protected readonly service: IdentityProviderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "IdentityProvider",
    action: "read",
    possession: "any",
  })
  async _identityProvidersMeta(
    @graphql.Args() args: IdentityProviderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [IdentityProvider])
  @nestAccessControl.UseRoles({
    resource: "IdentityProvider",
    action: "read",
    possession: "any",
  })
  async identityProviders(
    @graphql.Args() args: IdentityProviderFindManyArgs
  ): Promise<IdentityProvider[]> {
    return this.service.identityProviders(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => IdentityProvider, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "IdentityProvider",
    action: "read",
    possession: "own",
  })
  async identityProvider(
    @graphql.Args() args: IdentityProviderFindUniqueArgs
  ): Promise<IdentityProvider | null> {
    const result = await this.service.identityProvider(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => IdentityProvider)
  @nestAccessControl.UseRoles({
    resource: "IdentityProvider",
    action: "delete",
    possession: "any",
  })
  async deleteIdentityProvider(
    @graphql.Args() args: DeleteIdentityProviderArgs
  ): Promise<IdentityProvider | null> {
    try {
      return await this.service.deleteIdentityProvider(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
